### ISSUE TITLE
Feature: Home page UI

### ISSUE THREAD

**Issue by kanta1207** [twotter-app/twotter-frontend#2]
### Type of feature

🚀 Feature

### Description

Create the whole UI of Home page. 
You can skip implementing data fetching functionality for now.
It's not necessary to break it down into components from the beginning.

The components listed below are just examples. You can add to/ delete from them

### Tasks

- [x] Sidebar Component
- [x] Twoot component (Post component)
- [x] Timeline component (Composed of  multiple Twoot components)
- [x] Search bar component
