### ISSUE TITLE
Feature: Post a twoot(post), save it to backend

### ISSUE THREAD

**Issue by kanta1207** [twotter-app/twotter-frontend#4]
### Type of feature

🚀 Feature

### Description

Post a twoot(post), save it to backend
Validation : 1 - 140 word count

### Tasks

- [x] Create a form component for laptop to post a twoot
- [x] Create a form component for mobile to post a twoot
- [x] create POST API functionality
- [x] WordCount validation
